export const API_CONFIG = {
  VERSION: 'v1',
  BASE_URL: process.env.REACT_APP_API_URL || 'http://localhost:3000/api',
  CLIENT_TYPE: 'admin',
  TIMEOUT: 10000,
};

export const ENDPOINTS = {
  auth: {
    login: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/auth/login`,
    logout: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/auth/logout`,
    refresh: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/auth/refresh`,
    register: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/auth/register`,
    forgotPassword: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/auth/forgot-password`,
    resetPassword: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/auth/reset-password`,
    profile: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/auth/profile`,
  },
  users: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/users`,
    get: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/users/${id}`,
    update: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/users/${id}`,
    delete: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/users/${id}`,
  },
  sosAlerts: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/sos-alerts`,
    get: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/sos-alerts/${id}`,
    resolve: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/sos-alerts/${id}/resolve`,
    notify: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/sos-alerts/${id}/notify`,
    emergencyContact: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/sos-alerts/${id}/emergency-contact`,
  },
  families: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/families`,
    get: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/families/${id}`,
    create: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/families`,
    update: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/families/${id}`,
    delete: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/families/${id}`,
    notify: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/families/${id}/notify`,
  },
  devices: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/devices`,
    get: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/devices/${id}`,
    create: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/devices`,
    update: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/devices/${id}`,
    toggle: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/devices/${id}/toggle`,
    delete: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/devices/${id}`,
  },
  tracking: {
    locations: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/tracking/locations`,
    family: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/tracking/family/${familyId}`,
    user: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/tracking/user/${userId}`,
    userHistory: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/tracking/user/${userId}/history`,
    updateLocation: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/tracking/user/${userId}/location`,
    predict: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/tracking/user/${userId}/predict`,
    status: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/tracking/user/${userId}/status`,
    nearby: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/tracking/nearby`,
    geofences: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/tracking/geofences`,
    geofence: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/tracking/geofences/${id}`,
    heatmap: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/tracking/heatmap`,
  },
  content: {
    tips: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/tips`,
    tip: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/tips/${id}`,
    addTip: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/tips`,
    updateTip: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/tips/${id}`,
    deleteTip: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/tips/${id}`,
    articles: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/articles`,
    article: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/articles/${id}`,
    addArticle: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/articles`,
    updateArticle: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/articles/${id}`,
    deleteArticle: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/articles/${id}`,
    tutorials: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/tutorials`,
    tutorial: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/tutorials/${id}`,
    createTutorial: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/tutorials`,
    updateTutorial: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/tutorials/${id}`,
    deleteTutorial: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/tutorials/${id}`,
    news: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/news`,
    newsItem: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/news/${id}`,
    createNews: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/news`,
    updateNews: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/news/${id}`,
    deleteNews: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/news/${id}`,
    laws: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/laws`,
    law: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/laws/${id}`,
    createLaw: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/laws`,
    updateLaw: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/laws/${id}`,
    deleteLaw: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/laws/${id}`,
    helplines: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/helplines`,
    helpline: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/helplines/${id}`,
    createHelpline: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/helplines`,
    updateHelpline: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/helplines/${id}`,
    deleteHelpline: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/content/helplines/${id}`,
  },
  settings: {
    get: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/settings`,
    update: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/settings`,
  },
  analytics: {
    stats: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/analytics/stats`,
    data: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/analytics`,
  },
  activity: {
    logs: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/activity`,
  },
  grievance: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/grievance`,
    get: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/grievance/${id}`,
    updateStatus: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/grievance/${id}/status`,
    assign: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/grievance/${id}/assign`,
    delete: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/grievance/${id}`,
    stats: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/grievance/stats`,
  },
  menus: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/menus`,
    get: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/menus/${id}`,
    create: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/menus`,
    update: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/menus/${id}`,
    delete: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/menus/${id}`,
  },
  qr: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/qr/all`,
    revoke: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/qr/revoke/${id}`,
    forceGrant: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/qr/force-grant`,
    accessLogs: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/qr/access-logs`,
  },
  safeRoute: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/safe-route/all`,
    stats: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/safe-route/stats`,
    hotspots: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/safe-route/hotspots`,
  },
  themes: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/themes`,
    stats: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/themes/stats`,
    userPreferences: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/themes/user-preferences`,
    setUserPreference: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/themes/user-preference`,
    get: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/themes/${id}`,
    create: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/themes`,
    update: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/themes/${id}`,
    delete: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/themes/${id}`,
    setDefault: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/themes/${id}/default`,
  },
  childcare: {
    children: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/childcare/children`,
    child: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/childcare/children/${id}`,
    createChild: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/childcare/children`,
    updateChild: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/childcare/children/${id}`,
    schedules: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/childcare/schedules`,
    deleteSchedule: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/childcare/schedules/${id}`,
    alerts: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/childcare/alerts`,
    schoolZones: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/admin/childcare/school-zones`,
  },
};

export default ENDPOINTS;
